Dubrova2507
SeleniumQALight/G26NewProject pull request #109
Opened 2017-07-25 18:56 UTC by elfe1919

@tradulenko 
Title check added

2017-07-25 19:04 UTC, tradulenko requested changes

2017-07-25 19:04 UTC, tradulenko commented on G26NewProject/DubrovaProj/src/main/java/pages/MainPage.java
> +    public WebElement Avatar;
Имя объектов с маленькой буквы

2017-07-25 19:04 UTC, tradulenko commented on G26NewProject/DubrovaProj/src/main/java/pages/MainPage.java
> +      webDriver.findElement(By.xpath(".//img[@class='user-image']")).click();
Тут наверное уже нужно не локатор , а елемент использовать

2017-07-25 19:04 UTC, tradulenko commented on G26NewProject/DubrovaProj/src/test/java/parentTest/ParentTestLoginSetUp.java
> +        //checkAC("Text 'Учет запчастей' not found", loginPage.isElementWithTextPresent("Учет запчастей"),true);
Тут наверное можно удалить закомментированный код

2017-07-26 19:13 UTC, elfe1919 commented on G26NewProject/DubrovaProj/src/main/java/pages/MainPage.java
> +      webDriver.findElement(By.xpath(".//img[@class='user-image']")).click();
Пока не получится, потому что тогда фейлится тест. Нужно использовать wait , потому как кнопка логаут находится на выпадающем поп-апе

2017-07-29 10:00 UTC, elfe1919 commented
merge conflict resolved

2017-07-29 10:00 UTC, elfe1919 commented
@tradulenko 
MC resolved

2017-08-28 07:28 UTC, SeleniumQALight commented
very old request

2017-08-28 07:28 UTC, closed without merging